from pathlib import Path


VECTOR_SIZE=128
CLASSIFIER_EPOCHS = 100
CLASSIFIER_DROPOUT=0.3
CLASSIFIER_HIDDEN_SIZE = 32

BERT_EPOCHS =100
BERT_NAME = Path("tiny_bert_from_scratch_simple")
BERT_MAXLEN = 10
BERT_BATCHSIZE=10000



DEBUG=False
